import '../styles/globals.css'
import Head from 'next/head'
import Script from 'next/script'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Head>
        {/* Google tag (gtag.js) */}
            <Script async src="https://www.googletagmanager.com/gtag/js?id=G-FQXEB0FYX5"></Script>
            <Script>
                {`
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());

                    gtag('config', 'G-FQXEB0FYX5');
                `}
            </Script>
      </Head>
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  )
}
