export const featuredUnis = [
    {
        university: "Texas Christian University",
        location: "Fort Worth, TX",
        headline: "Horned Frogs",
        student_rep: "Payton Cranford",
        summary: "TCU began as a progressive and personal college for men and women with a dream to learn and lead 150 years later, we are still that place.",
        image: '/featured_unis/tcu.jpeg',
        website: "https://www.tcu.edu/",
    },
    {
        university: "Purdue University",
        location: "West Lafayette, IN",
        headline: "Boilermakers",
        student_rep: "Cameron Robinson",
        summary: "For over 150 years, generations of Boilermakers have left their mark in small steps and giant leaps. Today, we continue in those footsteps as we bring our best and learn to build a better world, together.",
        image: '/featured_unis/purdue.jpg',
        website: "https://www.purdue.edu/",
    },
    {
        university: "Southern Methodist University",
        location: "Dallas, TX",
        headline: "Mustangs",
        student_rep: "Daja White",
        summary: "The optimistic outlook of Dallas is at the heart of SMU. For more than a century, SMU\'s enterprising spirit has helped shape Dallas into a global gateway for people of all backgrounds who want to change the world.",
        image: '/featured_unis/smu.jpeg',
        website: "https://www.smu.edu/",
    },
    {
        university: "Northeastern University",
        location: "Boston, MA",
        headline: "Huskies",
        student_rep: "Max Berger",
        summary: "Founded in 1898, we\'re renowned for our experiential learning model, high-impact research, deep partnerships, and worldwide reach. From day one, we\'ve pursued innovative ways of teaching and research that place a premium on experience and engagement with the world.",
        image: '/featured_unis/northeastern.jpg',
        website: "https://www.northeastern.edu/",
    },
    {
        university: "George Washington University",
        location: "Washington, D.C.",
        headline: "Revolutionaries",
        student_rep: "Sydney Formby",
        summary: "Housed in a city unlike any other, our students gain an education unlike any other. The whole city is our classroom, and our students emerge not just with a diploma, but with experiences that could only happen at GW.",
        image: '/featured_unis/gwu.jpg',
        website: "https://www.gwu.edu/",
    },
    {
        university: "Howard University",
        location: "Washington, D.C.",
        headline: "Bisons",
        student_rep: "Khalib Davis",
        summary: "The University remains committed to further enhancing its strategic positioning as one of the top research universities in the nation. As we celebrate 154 years, we are uniquely positioned to have the next 150 years as glorious as the past.",
        image: '/belmont.jpg',
        wesbite: "https://howard.edu/",
    },
]